name: load_items
description: Load more items when scrolling to the bottom of a ListView or GridView.
version: 0.3.0
homepage: https://github.com/erf/load_items

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter: