name: load_items
description: Load more items when scrolling to the bottom of a ListView or GridView.
version: 0.4.0
homepage: https://github.com/erf/load_items

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter: